### ISSUE TITLE
Using fetch creates a pre-flight OPTIONS request

### ISSUE THREAD

**Issue by aysark** [hasura/react-check-auth#20]
Other than changing the server API to accept OPTIONS, is there a better to handle this from the client?

**Comment by karthikvt26** [comment]
If you are making a requests to `b.com` from `a.com` using the client. Then server must allow cross domain requests and respond to `OPTIONS` request (This is issued automatically by the browser whenever it encounters async requests made to different domain) with `200` status code whereas if you are making a request from the same domain (from `a.com` request is made to `a.com/user/info`) then server doesn't need to support `OPTIONS` request and everything will work.
