### ISSUE TITLE
Oauth2 Password flow

### ISSUE THREAD

**Issue by Webdesignwill** [hasura/react-check-auth#21]
It's not clear where to store the refresh token once the user logs in using a login form. Once the user enters their credentials and receives a token, where then should the token be saved?

**Comment by karthikvt26** [comment]
@Webdesignwill That decision is left to the developer. But ideally you store it in the localStorage and manage it.

**Comment by Webdesignwill** [comment]
Thanks for the reply. Got there in the end, nice work

**Comment by karthikvt26** [comment]
Woohooo :tada: :tada: thank you :)
