### ISSUE TITLE
 Functions are not valid as a React child

### ISSUE THREAD

**Issue by laureanoarcanio** [hasura/react-check-auth#22]
HI, thanks for this cool project. 
Started a new create-react-app project and followed your instructions,

```
<AuthProvider authUrl={authConfig.authUrl} reqOptions={authConfig.reqOptions}>
    <div>
      {({userInfo, isLoading, error}) => (
        userInfo ?
          (<span>Hi {userInfo.username}</span>) :
          (<a href="/login">Login</a>)
      )}
    </div>
  </AuthProvider>
```

And it looks like context API isn't working for me (or kind of), as I get following warning and me not logged in message dos not show up.

index.js:1452 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

My API returns a 401,  like this

{message: "Invalid token."}

Packages versions:
    "@material-ui/core": "^3.2.0",
    "@material-ui/icons": "^3.0.1",
    "connected-react-router": "4.5.0",
    "material-ui-icons": "^1.0.0-beta.36",
    "node-sass": "^4.9.3",
    "promise-polyfill": "^8.1.0",
    "react": "16.5.2",
    "react-check-auth": "^0.2.0-alpha.2",
    "react-dom": "16.5.2",
    "react-redux": "5.0.7",
    "react-router": "4.3.1",
    "react-router-dom": "4.3.1",
    "redux": "4.0.0",
    "redux-thunk": "2.3.0",
    "sanitize.css": "7.0.3",
    "serve": "10.0.2",
    "whatwg-fetch": "^3.0.0"

Any suggestions help, very much appreciated

**Comment by karthikvt26** [comment]
Hello thank you for your kind words :)

It looks like “children” of div is a render prop which is what the problem I am guessing. Please import “AuthConsumer” from the lib and it accepts a render prop

Here is a sample which you can refer to: https://github.com/hasura/react-check-auth/blob/master/README.md#2-show-a-welcome-user-or-a-login-button

Please let me know if you are facing any issues :)

**Comment by laureanoarcanio** [comment]
Thanks very much! I realised I forgot to import AuthConsumer, I also saw code example in repo. Probably good idea to link in the readme to it ?.

Thanks a lot, looks like a great way to do authentication
