### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_0_react___default.a.createContext is not a function

### ISSUE THREAD

**Issue by Ashwini-Kadam** [hasura/react-check-auth#24]
I want to used context with two component, created context in parent as :+1:   
export const settingContext = React.createContext(null); 
created context and use that context with settingValue which is true, ProviderInfo is component
<settingContext.Provider value={settingValue}>
      <ProviderInfo/>
</settingContext.Provider>
I have setstate the settingValue to true.
And in ProviderInfo component use it like : 
<settingContext.Consumer>
        {this.props.settingValue? <setting/>:''}
</settingContext.Consumer>
But I'm getting this kind of error.

**Comment by karthikvt26** [comment]
@Ashwini-Kadam looks like this has to do with the React version installed. It is available only with React versions > 16.3. 

Checkout [this out](https://github.com/facebook/react/releases) for more info

**Comment by ahsanfarooq3423** [comment]
this might help
`npm update react react-dom `

**Comment by IbrahimShamma99** [comment]
It is actually a version miss match so updating the your react-dom, react & redux packages would solve the issue

**Comment by piyushraj15** [comment]
> this might help
> `npm update react react-dom `

Its works

**Comment by corey-mitchell** [comment]
Updating react and react-dom did not work for me. I even tried downgrading react-redux from 7.2.0 to 5.x.x and that didn't work for me either.

I'm using react 16.13.1 and react-redux 7.2.0. Still getting this error. Any suggestions??

**Comment by shujathaliirfan** [comment]
thanks guys the above command really worked for me ....................

**Comment by VladyslavHorbachenko** [comment]
npm update react react-dom Perfect!!!!

**Comment by mechanicMo** [comment]
> npm update react react-dom

Thanks, this worked for me too!

**Comment by RajAakash** [comment]
> this might help
> `npm update react react-dom `

perfectly works!

**Comment by Whitetailss** [comment]
yes it works

**Comment by NealDeng77** [comment]
Thanks !

**Comment by Ketna20** [comment]
yes it worked! Thank you!

**Comment by timtim-us** [comment]
It worked. Thanks!

**Comment by Mozeloper** [comment]
thanks this worked for me also

**Comment by manickaa** [comment]
Thanks! That was really helpful :)

**Comment by znokdieline** [comment]
ohhhhh!!!! si funcionó!!!!

> this might help
> `npm update react react-dom `

**Comment by KenNguyen08** [comment]
Thank you, the command solved my issue.

**Comment by bhabalomkar421** [comment]
thanks......updating react and react-dom work.....

**Comment by ketanmandlik** [comment]
thank you..! it works by updating react and react-dom as well.

**Comment by ikechukwuakuma316** [comment]
Impressive!!! It works

**Comment by EdmundsEcho** [comment]
I hit a similar error using react v16.9.0 and react-dom 16.13.1... Upgrading was moot (already using one of the latest), and did not solve the issue.

**Comment by TheFe91** [comment]
> this might help
> `npm update react react-dom `

you saved my day!! Thank you!

**Comment by lbp003** [comment]
> this might help
> `npm update react react-dom `

Thank you

**Comment by oneandthebest** [comment]
> this might help
> `npm update react react-dom `

it really works, thank you

**Comment by james405** [comment]
did not work for me. also did npm cache verify after. still giving error.

**Comment by baylonflorymae** [comment]
Thanks. This 

> this might help
> `npm update react react-dom `

Thanks. it really works.

**Comment by hirensavani-99** [comment]
npm update react react-dom is working for me 
Thank you

**Comment by deionstfleur** [comment]
It didn't work for me. I still get the error.

**Comment by S-P-Ks** [comment]
> It didn't work for me. I still get the error.

Yay me too

**Comment by kingsleynwoye** [comment]
Thanks, guys it really works for me

**Comment by VladislavKorecky** [comment]
I got the same issue but updating react and react-dom didn't help. I was using NextJS 13 with react-hook-form and the problem was that I forgot to put "use client" on the top of the page. This error occurred because you can't use hooks in server components.

**Comment by indigoscipio** [comment]
thanks it work mate

**Comment by ssaminov** [comment]
no work
