### ISSUE TITLE
TypeError: o.default.createContext is not a function

### ISSUE THREAD

**Issue by kuroljov** [hasura/react-check-auth#7]
I have `create-react-app` with `react-scripts 1.1.4`. Now when I am importing this module like

```js
import { AuthProvider } from 'react-check-auth'
```

It gives me this

```
TypeError: o.default.createContext is not a function

(anonymous function)
node_modules/react-check-auth/build/index.js:1
```

**Comment by karthikvt26** [comment]
Hello,

`react-check-auth` uses context API which is part of `react` version > 16.3. Please upgrade your `react` and `react-dom` to versions > 16.3 and try again.

**Comment by kuroljov** [comment]
@karthikvt26 it worked! Thanks

**Comment by vidhiamin** [comment]
I have updated the react and react-dom but still it is giving me the same error. Can you please tell me what is the reason?

**Comment by suwu150** [comment]
> @karthikvt26 it worked! Thanks

How do you solve it? Is it an upgraded version?

**Comment by jcrommar** [comment]
run `npm update` this updated react-dom for me and then I ran `npm update react` this fixed it for me.

package.json now reads

 "react": "^16.8.6",
 "react-dom": "^16.8.6",

**Comment by sidjoyjr007** [comment]
Update **react and** **react-dom** package to the latest version (

> >16.3

) using **`npm update react react-dom`** then stop development server and restart it.

**Comment by naveenrawat51** [comment]
you need to downgrade react-redux to v5.x.x or upgrade react and react-dom to v16.4 or above

If you are using yarn, you can run

yarn upgrade react react-dom
else with npm you can run

npm update react react-dom
You could also change the versions manually in package.json and run yarn install or npm install
